# Generated by Django 4.1.4 on 2022-12-28 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_client_contract_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='company_name',
            field=models.CharField(default='toma', max_length=250),
            preserve_default=False,
        ),
    ]
