# Generated by Django 4.1.4 on 2023-01-18 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_contract_payment_due'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_status',
            field=models.BooleanField(default=False, verbose_name='Converted'),
        ),
    ]
